name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'
      - run: sudo apt-get install wabt
      - run: yarnpkg --pure-lockfile
      - run: yarnpkg build
      - run: yarnpkg lint
      - run: yarnpkg test --coverage
